
engines:
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
  eslint:
    enabled: true
  fixme:
    enabled: true
  rubocop:
    enabled: true 
exclude_paths:
- "plugins/"
- "jSQL.js"
- "tests/"
- "Gruntfile.js"
- "LICENSE"
- "README.md"
- "jSQL.min.js"
- "package.json"
