
engines:
  rubocop:
    enabled: true
  eslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - javascript:
exclude_paths:
- "**/plugins/"
- "**/src/"
- "**/tests/"
- "Gruntfile.js"
- "LICENSE"
- "README.md"
- "jSQL.min.js"
- "package.json"
